name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    # disallows two or more release jobs to run in parallel
    concurrency: release

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'

    - name: Bump version and release to PyPi
      run: |
        make venv
        git config --global user.name 'Double.Cloud Bot'
        git config --global user.email 'bot@double.cloud'
        make release
      env:
        REPOSITORY_USERNAME: __token__
        REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}